name: Build and Publish agilebeat/proxy-plus-koa-based container

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      security-events: write

    steps:
    - uses: actions/checkout@v4
    - name: Build and test kubectl container
      run: |
        DOCKER_IMAGE=agilebeat/proxy-plus-koa-based GIT_BRANCH=${GITHUB_REF#refs/heads/} make docker_build
        DOCKER_IMAGE=agilebeat/proxy-plus-koa-based GIT_BRANCH=${GITHUB_REF#refs/heads/} make test

    - name: Trivy scan container image
      uses: aquasecurity/trivy-action@0.24.0
      with:
        scan-type: image
        image-ref: agilebeat/proxy-plus-koa-based:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
        format: sarif
        output: trivy-image.sarif
        severity: HIGH,CRITICAL
        limit-severities-for-sarif: true
        ignore-unfixed: true

    - name: Upload Trivy SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-image.sarif
    - name: Docker meta
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: agilebeat/proxy-plus-koa-based
        tag-semver: |
          {{raw}}
    - name: Set up QEMU
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/setup-buildx-action@v1
    - name: install cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v2.5.2'
    - name: Login to DockerHub
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and publish multi-arch kubectl container
      id: build_and_publish
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64, linux/arm64, linux/ppc64le, linux/s390x
        push: true
        tags: |
          ${{ github.ref != 'refs/heads/main' && steps.docker_meta.outputs.tags || '' }}
          ${{ github.ref == 'refs/heads/main' && 'agilebeat/proxy-plus-koa-based:latest' || '' }}
        labels: ${{ steps.docker_meta.outputs.labels }}
    - name: Sign image only on version branches
      if: ${{ startsWith(github.ref, 'refs/heads/v') }}
      run: cosign sign --yes --oidc-issuer https://token.actions.githubusercontent.com agilebeat/proxy-plus-koa-based@${{ steps.build_and_publish.outputs.digest }}
      env:
        COSIGN_EXPERIMENTAL: 1
